
baseURL = "https://fuzznotes.github.io/"
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"
title = "Fuzz Notes"
subtitle = "Tech, Home Automation, and other ramblings"
author = "Fuzz"
languageCode = "en"
languageName = "English"
hasCJKLanguage = false

[params]
defaultTheme = "auto"
fingerprint = ""
dateFormat = "2006-01-02"
title = "Fuzz Notes"
subtitle = "Tech, Home Automation, and other ramblings"
description = "Tech, Home Automation, and other ramblings"

[params.header.title]
name = "Fuzz Notes - Tech, Home Automation, etc"

# Menu config
[menu]
[[menu.main]]
weight = 1
identifier = "posts"
pre = ""
post = ""

name = "Posts"
url = "/posts/"
title = "All Posts"

[[menu.main]]
weight = 2
identifier = "tags"
name = "Tags"
url = "/tags/"
title = "Posts by Tag"

[[menu.main]]
weight = 3
identifier = "about"
name = "About"
url = "/about/"
title = "About Fuzz Notes"

# Pagination config
[pagination]
disableAliases = false
pagerSize = 10
path = "page"

[params.PostAuthor]
enable = false

[params.footer]
hugo = false
author = false
since = "2025"

[params.home.profile]
subtitle = "Some miscellaneous thoughts ..."

[params.page.share]
enable = false

# Markup related configuration in Hugo
[markup]

# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]

# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false